### ISSUE TITLE
packer build: unexpected EOF

### ISSUE THREAD

**Issue by petercrocker** [mweisel/veos-lab-vagrant-libvirt#1]
I can't seem to get the `packer build` step to succeed. Curious what host environment and versions of packer you're using?

```# packer version
Packer v1.5.1```

`packer build -debug -var 'version=4.23.1F' arista-veos-lab.json`


```
==> qemu: Waiting for shutdown...
2020/01/04 13:33:03 packer-builder-qemu plugin: Qemu stderr: KVM: injection failed, MSI lost (Operation not permitted)
2020/01/04 13:33:03 packer-builder-qemu plugin: VM shut down.
2020/01/04 13:33:03 packer-builder-qemu plugin: failed to unlock port lockfile: close tcp 127.0.0.1:5965: use of closed network connection
2020/01/04 13:33:03 [INFO] (telemetry) ending qemu
2020/01/04 13:33:03 [INFO] (telemetry) Starting post-processor vagrant
==> qemu: Running post-processor: vagrant
==> qemu (vagrant): Creating Vagrant box for 'libvirt' provider
    qemu (vagrant): Copying from artifact: vEOS-4.23.1F/vEOS-4.23.1F
Build 'qemu' errored: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Some builds didn't complete successfully and had errors:
--> qemu: 1 error(s) occurred:

* Post-processor failed: unexpected EOF

==> Builds finished but no artifacts were created.
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: panic: interface conversion: interface {} is string, not uint64
2020/01/04 13:33:04 packer-post-processor-vagrant plugin:
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: goroutine 73 [running]:
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: github.com/hashicorp/packer/post-processor/vagrant.(*LibVirtProvider).Process(0x6ee3e90, 0x4815640, 0xc0002602a0, 0x48156a0, 0xc00000c100, 0xc000052400, 0x14, 0x0, 0xc00043b858, 0x42d681, ...)
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/Users/mmarsh/Projects/packer/post-processor/vagrant/libvirt.go:31 +0x927
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: github.com/hashicorp/packer/post-processor/vagrant.(*PostProcessor).PostProcessProvider(0xc00046c180, 0x410880b, 0x7, 0x47c4200, 0x6ee3e90, 0x4815640, 0xc0002602a0, 0x48156a0, 0xc00000c100, 0x0, ...)
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/Users/mmarsh/Projects/packer/post-processor/vagrant/post-processor.go:126 +0x5a7
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: github.com/hashicorp/packer/post-processor/vagrant.(*PostProcessor).PostProcess(0xc00046c180, 0x47fa500, 0xc000116040, 0x4815640, 0xc0002602a0, 0x48156a0, 0xc00000c100, 0x1, 0x203000, 0x28, ...)
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/Users/mmarsh/Projects/packer/post-processor/vagrant/post-processor.go:185 +0x11e
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: github.com/hashicorp/packer/packer/rpc.(*PostProcessorServer).PostProcess(0xc0003000c0, 0x1, 0xc0005a2030, 0x0, 0x0)
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/Users/mmarsh/Projects/packer/packer/rpc/post_processor.go:109 +0x277
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: reflect.Value.call(0xc000112720, 0xc000110780, 0x13, 0x41034fe, 0x4, 0xc0002f7f18, 0x3, 0x3, 0x0, 0x6ecaf00, ...)
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/usr/local/go/src/reflect/value.go:460 +0x5f6
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: reflect.Value.Call(0xc000112720, 0xc000110780, 0x13, 0xc0001c1718, 0x3, 0x3, 0xc00016e870, 0xc00046e2b0, 0xc)
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/usr/local/go/src/reflect/value.go:321 +0xb4
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: net/rpc.(*service).call(0xc000300100, 0xc00016e0a0, 0xc0005be030, 0xc0005be040, 0xc0001e6200, 0xc0003561c0, 0x34cc100, 0xc00046e2b0, 0x18a, 0x3373dc0, ...)
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/usr/local/go/src/net/rpc/server.go:377 +0x16f
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: created by net/rpc.(*Server).ServeCodec
2020/01/04 13:33:04 packer-post-processor-vagrant plugin: 	/usr/local/go/src/net/rpc/server.go:474 +0x42b
2020/01/04 13:33:04 [INFO] (telemetry) ending vagrant
2020/01/04 13:33:04 /usr/bin/packer: plugin process exited
2020/01/04 13:33:04 Deleting original artifact for build 'qemu'

* Post-processor failed: unexpected EOF
2020/01/04 13:33:04 machine readable: error-count []string{"1"}
==> Some builds didn't complete successfully and had errors:
2020/01/04 13:33:04 machine readable: qemu,error []string{"1 error(s) occurred:\n\n* Post-processor failed: unexpected EOF"}

* Post-processor failed: unexpected EOF
==> Builds finished but no artifacts were created.
2020/01/04 13:33:04 [INFO] (telemetry) Finalizing.
2020/01/04 13:33:05 waiting for all plugin processes to complete...
2020/01/04 13:33:05 /usr/bin/packer: plugin process exited
```

**Comment by mweisel** [comment]
https://github.com/hashicorp/packer/issues/8545

Use `1.4.5` until the bug is fixed in an upcoming Packer release.

**Comment by petercrocker** [comment]
That did it, awesome, thanks!
